### ISSUE TITLE
Add password to game options

### ISSUE THREAD

**Issue by MGageMorgan** [devgianlu/PYX-Reloaded#62] opened 2018-02-11 20:11 UTC
This is a pretty obvious one - but only after people who use this remember that they don't want randos to join their game lol

**Comment by devgianlu** [comment] 2018-02-11 20:13
Duplicate of #55

**Comment by MGageMorgan** [comment] 2018-02-11 20:14
Oops shit sorry...didn't realize that was already in the works 😂😂

**Closed by devgianlu** 2018-02-11 20:13 UTC
